### ISSUE TITLE
Dev dependencies out of date.

### ISSUE THREAD

**Issue by govindrai** [fiznool/body-parser-xml#3]
Hi Could you update your dev dependencies, as they are out of date. This is a great module and I would hate for it to break down! Thanks!

**Comment by fiznool** [comment]
Hi,

As you [can see here](https://david-dm.org/fiznool/body-parser-xml?type=dev) the dev dependencies that are out of date are mocha and supertest. Updating these would probably cause breaking changes to the tests which unfortunately I don't have time to fix right now.

If you'd like to submit a PR with these updated I'd be very happy to accept. But in the meantime I don't think you need to worry too much, these are only used when the package's unit tests are run on the CI server, they won't have any impact in production.

Thanks!
