### ISSUE TITLE
Support bodyparser's 'type' option as function

### ISSUE THREAD

**Issue by Equals182** [fiznool/body-parser-xml#5]
This module uses `bodyparser.text()` to parse body as text and passes `options` object to configure it.

As you can see [here](https://www.npmjs.com/package/body-parser#type), bodyparser accepts `options.type` options as function, which allows user to control type matching precisely.

Unfortunately, in body-parser-xml [there is a line](https://github.com/fiznool/body-parser-xml/blob/master/index.js#L18) where it check if passed `options.type` is not an array and convert it into array thus breaking default bodyparser.text()'s ability to use user's function, because that function [checks if passed 'type' option is a function](https://github.com/expressjs/body-parser/blob/master/lib/types/text.js#L49)

**Comment by fiznool** [comment]
Fixed in v2.0.0
