### ISSUE TITLE
🚨 Potential Prototype Pollution

### ISSUE THREAD

**Issue by huntr-helper** [fiznool/body-parser-xml#68]
👋 Hello, @fiznool - a potential high severity Prototype Pollution vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-fiznool/body-parser-xml** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by huntr-helper** [comment]
📦 A patch has been submitted for this report. 🔗 Check the patch (https://github.com/fiznool/body-parser-xml/compare/HEAD...yadhukrishnam:master) or visit the advisory page (https://huntr.dev/bounties/1-other-fiznool/body-parser-xml) for more information.

**Comment by fiznool** [comment]
Fixed in #69
